<?php 
header('content-type: text/javascript');
require('../config.php');
?>
//<script>
/* DO NOT EDIT THIS FILE */
/* Edit config.php instead */

var config = <?= json_encode($config) ?>;

console.log("Loaded configuration");

